FROM tuplestream/swift-env AS build

WORKDIR /build
COPY . .
RUN swift build -c release

FROM swift:5.2-slim AS runtime

COPY --from=build /build/.build/release/IntegrationTestRunner /usr/local/bin/IntegrationTestRunner

CMD ["IntegrationTestRunner"]
