#if !canImport(ObjectiveC)
import XCTest

extension BloomFilterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BloomFilterTests = [
        ("testAddSingleItem", testAddSingleItem),
        ("testInitSIMDFilter", testInitSIMDFilter),
    ]
}

extension CommonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommonTests = [
        ("testCRC32", testCRC32),
        ("testInvalidPort", testInvalidPort),
        ("testValidPort", testValidPort),
    ]
}

extension HashingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HashingTests = [
        ("testAddSingleItem", testAddSingleItem),
        ("testItemHashLargerThanAvailable", testItemHashLargerThanAvailable),
        ("testLargeRing", testLargeRing),
        ("testMurmurBasicCases", testMurmurBasicCases),
        ("testMurmurCollision", testMurmurCollision),
        ("testXXHashBasicCases", testXXHashBasicCases),
        ("testXXHashEmptyInput", testXXHashEmptyInput),
        ("testXXHashLargeInput", testXXHashLargeInput),
    ]
}

extension MembershipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MembershipTests = [
        ("testSpinUpK8sTracker", testSpinUpK8sTracker),
    ]
}

extension PhiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PhiTests = [
        ("testHeartbeat", testHeartbeat),
        ("testPhiUninitialized", testPhiUninitialized),
    ]
}

extension StatemachineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StatemachineTests = [
        ("testInit", testInit),
        ("testTransitionTwoStateMachine", testTransitionTwoStateMachine),
    ]
}

extension TreesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TreesTests = [
        ("testInit", testInit),
        ("testTransitionTwoStateMachine", testTransitionTwoStateMachine),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BloomFilterTests.__allTests__BloomFilterTests),
        testCase(CommonTests.__allTests__CommonTests),
        testCase(HashingTests.__allTests__HashingTests),
        testCase(MembershipTests.__allTests__MembershipTests),
        testCase(PhiTests.__allTests__PhiTests),
        testCase(StatemachineTests.__allTests__StatemachineTests),
        testCase(TreesTests.__allTests__TreesTests),
    ]
}
#endif
