#if !canImport(ObjectiveC)
import XCTest

extension BloomFilterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BloomFilterTests = [
        ("testAddSingleItem", testAddSingleItem),
        ("testInitSIMDFilter", testInitSIMDFilter),
    ]
}

extension StatemachineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StatemachineTests = [
        ("testInit", testInit),
        ("testTransitionTwoStateMachine", testTransitionTwoStateMachine),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BloomFilterTests.__allTests__BloomFilterTests),
        testCase(StatemachineTests.__allTests__StatemachineTests),
    ]
}
#endif
