version: 2.1

jobs:
  build:
    docker:
      - image: swift:5.1
    steps:
      - checkout
      - run: swift test
  validate:
    docker:
      - image: m0wfo/tailor:0.12.0
    steps:
      - checkout
      - run: tailor --format=json ~/project
      bump_version:
        docker:
          - image: tuplestream/bumpversion:latest
        steps:
          - add_ssh_keys:
              fingerprints:
                - "c8:96:78:e4:f0:49:4e:49:f8:f2:87:80:c5:a7:53:7c"
          - checkout
          - run:
              name: run bumpversion and push
              command: bump

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - validate
      - bump_version:
          requires:
            - build
            - validate
