version: 2.1

jobs:
  build:
    docker:
      - image: swift:5.1
    steps:
      - checkout
      - run: swift test
      - store_test_results:
          path: tests.xml
  validate:
    docker:
      - image: m0wfo/tailor:0.12.0
    steps:
      - checkout
      - run: tailor --format=json ~/project
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "61:ee:91:08:24:c9:72:a7:82:34:9a:c5:68:1e:11:f9"
      - checkout
      - run:
          name: run bumpversion and push
          command: bump

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - validate
      - bump_version:
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - validate
