version: 2.1

jobs:
  build:
    docker:
      - image: swift:5.1
    steps:
      - checkout
      - run: swift test --generate-linuxmain
      - run: swift test
  validate:
    docker:
      - image: m0wfo/tailor:0.12.0
    steps:
      - checkout
      - run: tailor --format=json ~/project

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - validate
