version: 2.1

jobs:
  build:
    docker:
      - image: swift:5.1
    steps:
      - checkout
      - run: swift test
  validate:
    docker:
      - image: m0wfo/tailor:0.12.0
    steps:
      - checkout
      - run: tailor --format=json ~/project
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7b:f0:f0:31:ac:72:de:1a:f1:10:7e:c3:dc:1e:be:2c"
      - checkout
      - run:
          name: run bumpversion and push
          command: bump

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - validate
      - bump_version:
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - validate
